// WitnessSkills: SM-2 Spaced Repetition Engine
// Inspired by balafons' SpacedRepetitionDashboard.tsx and SpacedRepetitionService.
// Extends the existing retention.ts (which uses a simpler interval table)
// with the full SM-2 algorithm used in Anki / SuperMemo.
//
// Key difference from retention.ts:
//   retention.ts  = per-node RCT learning state (unlocked, cleared, cret)
//   spacedRepetition.ts = per-skill review scheduling for the Skills portfolio

export const MS_PER_DAY = 24 * 60 * 60 * 1000;

// ---------------------------------------------------------------
// TYPES
// ---------------------------------------------------------------

export type ReviewQuality =
  | 0  // Complete blackout
    | 1  // Incorrect, but remembered on seeing answer
      | 2  // Incorrect, but easy to remember
        | 3  // Correct with serious difficulty
          | 4  // Correct after hesitation
            | 5; // Perfect recall

            export interface SM2Card {
              skillId: string;
                skillName: string;
                  /** Easiness factor — starts at 2.5, min 1.3 */
                    easinessFactor: number;
                      /** Number of successful repetitions */
                        repetitions: number;
                          /** Current interval in days */
                            intervalDays: number;
                              /** ISO timestamp of last review */
                                lastReviewedAt: string | null;
                                  /** ISO timestamp when next review is due */
                                    nextReviewAt: string;
                                      /** 0-100 estimated retention % (Ebbinghaus forgetting curve) */
                                        retentionPct: number;
                                          /** Memory strength 0-1 */
                                            memoryStrength: number;
                                            }

                                            export interface SM2ReviewResult {
                                              updated: SM2Card;
                                                wasOverdue: boolean;
                                                  retentionGained: number;
                                                  }

                                                  // ---------------------------------------------------------------
                                                  // SM-2 ALGORITHM
                                                  // ---------------------------------------------------------------

                                                  /**
                                                   * Apply one SM-2 review to a card.
                                                    * @param card   - current card state (or null for a brand new card)
                                                     * @param quality - reviewer self-assessment 0-5
                                                      * @param now     - review timestamp (ms, defaults to Date.now())
                                                       */
                                                       export function sm2Review(
                                                         card: SM2Card,
                                                           quality: ReviewQuality,
                                                             now: number = Date.now(),
                                                             ): SM2ReviewResult {
                                                               const prevRetention = card.retentionPct;
                                                                 const wasOverdue    = card.nextReviewAt ? now > new Date(card.nextReviewAt).getTime() : false;

                                                                   let { easinessFactor, repetitions, intervalDays } = card;

                                                                     if (quality < 3) {
                                                                         // Failed — reset
                                                                             repetitions  = 0;
                                                                                 intervalDays = 1;
                                                                                   } else {
                                                                                       // Passed — advance
                                                                                           if (repetitions === 0) {
                                                                                                 intervalDays = 1;
                                                                                                     } else if (repetitions === 1) {
                                                                                                           intervalDays = 6;
                                                                                                               } else {
                                                                                                                     intervalDays = Math.round(intervalDays * easinessFactor);
                                                                                                                         }
                                                                                                                             repetitions += 1;
                                                                                                                               }
                                                                                                                               
                                                                                                                                 // Update easiness factor
                                                                                                                                   easinessFactor = Math.max(
                                                                                                                                       1.3,
                                                                                                                                           easinessFactor + 0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02),
                                                                                                                                             );
                                                                                                                                             
                                                                                                                                               const nextReviewMs  = now + intervalDays * MS_PER_DAY;
                                                                                                                                                 const lastReviewedAt = new Date(now).toISOString();
                                                                                                                                                   const nextReviewAt   = new Date(nextReviewMs).toISOString();
                                                                                                                                                   
                                                                                                                                                     const retentionPct    = computeRetention(intervalDays, easinessFactor);
                                                                                                                                                       const memoryStrength  = retentionPct / 100;
                                                                                                                                                       
                                                                                                                                                         const updated: SM2Card = {
                                                                                                                                                             ...card,
                                                                                                                                                                 easinessFactor,
                                                                                                                                                                     repetitions,
                                                                                                                                                                         intervalDays,
                                                                                                                                                                             lastReviewedAt,
                                                                                                                                                                                 nextReviewAt,
                                                                                                                                                                                     retentionPct,
                                                                                                                                                                                         memoryStrength,
                                                                                                                                                                                           };
                                                                                                                                                                                           
                                                                                                                                                                                             return {
                                                                                                                                                                                                 updated,
                                                                                                                                                                                                     wasOverdue,
                                                                                                                                                                                                         retentionGained: retentionPct - prevRetention,
                                                                                                                                                                                                           };
                                                                                                                                                                                                           }
                                                                                                                                                                                                           
                                                                                                                                                                                                           /**
                                                                                                                                                                                                            * Create an initial SM2Card for a newly tracked skill.
                                                                                                                                                                                                             */
                                                                                                                                                                                                             export function createSM2Card(skillId: string, skillName: string): SM2Card {
                                                                                                                                                                                                               const now = Date.now();
                                                                                                                                                                                                                 return {
                                                                                                                                                                                                                     skillId,
                                                                                                                                                                                                                         skillName,
                                                                                                                                                                                                                             easinessFactor: 2.5,
                                                                                                                                                                                                                                 repetitions:    0,
                                                                                                                                                                                                                                     intervalDays:   1,
                                                                                                                                                                                                                                         lastReviewedAt: null,
                                                                                                                                                                                                                                             nextReviewAt:   new Date(now + MS_PER_DAY).toISOString(),
                                                                                                                                                                                                                                                 retentionPct:   100,
                                                                                                                                                                                                                                                     memoryStrength: 1.0,
                                                                                                                                                                                                                                                       };
                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                       // ---------------------------------------------------------------
                                                                                                                                                                                                                                                       // EBBINGHAUS FORGETTING CURVE
                                                                                                                                                                                                                                                       // ---------------------------------------------------------------
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                        * Estimate current retention % given how long since last review
                                                                                                                                                                                                                                                         * and the card's easiness factor (proxy for memory strength).
                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                           * R(t) = e^(-t / (S * EF))
                                                                                                                                                                                                                                                            * where S = stability constant (days), EF = easiness factor
                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                             export function computeRetention(
                                                                                                                                                                                                                                                               daysSinceReview: number,
                                                                                                                                                                                                                                                                 easinessFactor: number,
                                                                                                                                                                                                                                                                   stabilityBase: number = 14,
                                                                                                                                                                                                                                                                   ): number {
                                                                                                                                                                                                                                                                     const stability = stabilityBase * easinessFactor;
                                                                                                                                                                                                                                                                       const r = Math.exp(-daysSinceReview / stability);
                                                                                                                                                                                                                                                                         return Math.round(Math.max(0, Math.min(100, r * 100)));
                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                          * Compute live retention for a card based on current time.
                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                           export function liveRetention(card: SM2Card, now: number = Date.now()): number {
                                                                                                                                                                                                                                                                             if (!card.lastReviewedAt) return 100;
                                                                                                                                                                                                                                                                               const daysSince = (now - new Date(card.lastReviewedAt).getTime()) / MS_PER_DAY;
                                                                                                                                                                                                                                                                                 return computeRetention(daysSince, card.easinessFactor);
                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                 // ---------------------------------------------------------------
                                                                                                                                                                                                                                                                                 // SCHEDULING HELPERS
                                                                                                                                                                                                                                                                                 // ---------------------------------------------------------------
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                 /** Returns cards that are due for review (sorted: most overdue first) */
                                                                                                                                                                                                                                                                                 export function getDueCards(cards: SM2Card[], now: number = Date.now()): SM2Card[] {
                                                                                                                                                                                                                                                                                   return cards
                                                                                                                                                                                                                                                                                       .filter(c => new Date(c.nextReviewAt).getTime() <= now)
                                                                                                                                                                                                                                                                                           .sort((a, b) =>
                                                                                                                                                                                                                                                                                                 new Date(a.nextReviewAt).getTime() - new Date(b.nextReviewAt).getTime(),
                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                     /** Human-readable "due in X days" / "due now" / "X days overdue" */
                                                                                                                                                                                                                                                                                                     export function dueLabelFor(card: SM2Card, now: number = Date.now()): string {
                                                                                                                                                                                                                                                                                                       const dueMs  = new Date(card.nextReviewAt).getTime();
                                                                                                                                                                                                                                                                                                         const diffMs = dueMs - now;
                                                                                                                                                                                                                                                                                                           const diffDays = Math.round(Math.abs(diffMs) / MS_PER_DAY);
                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                             if (Math.abs(diffMs) < 60 * 60 * 1000) return 'Due now';
                                                                                                                                                                                                                                                                                                               if (diffMs < 0) return `${diffDays}d overdue`;
                                                                                                                                                                                                                                                                                                                 if (diffDays === 0) return 'Due today';
                                                                                                                                                                                                                                                                                                                   if (diffDays === 1) return 'Due tomorrow';
                                                                                                                                                                                                                                                                                                                     return `Due in ${diffDays}d`;
                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                     /** Urgency colour for a card */
                                                                                                                                                                                                                                                                                                                     export function cardUrgencyClass(card: SM2Card, now: number = Date.now()): string {
                                                                                                                                                                                                                                                                                                                       const live = liveRetention(card, now);
                                                                                                                                                                                                                                                                                                                         if (live < 40) return 'text-red-400';
                                                                                                                                                                                                                                                                                                                           if (live < 65) return 'text-amber-400';
                                                                                                                                                                                                                                                                                                                             return 'text-teal-400';
                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                             // ---------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                             // PERSISTENCE KEY (localStorage — Supabase sync is a future step)
                                                                                                                                                                                                                                                                                                                             // ---------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                             const STORAGE_KEY = 'ws_sm2_cards';
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                             export function loadSM2Cards(): SM2Card[] {
                                                                                                                                                                                                                                                                                                                               try {
                                                                                                                                                                                                                                                                                                                                   const raw = localStorage.getItem(STORAGE_KEY);
                                                                                                                                                                                                                                                                                                                                       if (!raw) return [];
                                                                                                                                                                                                                                                                                                                                           return JSON.parse(raw) as SM2Card[];
                                                                                                                                                                                                                                                                                                                                             } catch {
                                                                                                                                                                                                                                                                                                                                                 return [];
                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                   export function saveSM2Cards(cards: SM2Card[]): void {
                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                         localStorage.setItem(STORAGE_KEY, JSON.stringify(cards));
                                                                                                                                                                                                                                                                                                                                                           } catch {
                                                                                                                                                                                                                                                                                                                                                               // quota exceeded — fail silently
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                 export function upsertSM2Card(cards: SM2Card[], card: SM2Card): SM2Card[] {
                                                                                                                                                                                                                                                                                                                                                                   const idx = cards.findIndex(c => c.skillId === card.skillId);
                                                                                                                                                                                                                                                                                                                                                                     if (idx === -1) return [...cards, card];
                                                                                                                                                                                                                                                                                                                                                                       const next = [...cards];
                                                                                                                                                                                                                                                                                                                                                                         next[idx] = card;
                                                                                                                                                                                                                                                                                                                                                                           return next;
                                                                                                                                                                                                                                                                                                                                                                           }
