import { hydrateGenerated } from './domainGenerator';
import type { Domain } from './types';

// ---------------------------------------------------------------------------
// Git
// ---------------------------------------------------------------------------
export const GIT_DOMAIN: Domain = hydrateGenerated({
  name: 'Git',
  root: 'git-commit',
  grounded: true,
  nodes: [
    { id: 'git-commit', label: 'Commit & staging area',
      description: 'How the index (staging area) relates to commits and working tree.',
      tier: 'Junior', keywords: ['commit','stage','index','add','working tree','snapshot'],
      negativeKeywords: ['push','remote'], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-branch', label: 'Branching model',
      description: 'Branches as lightweight movable pointers to commits.',
      tier: 'Junior', keywords: ['branch','pointer','HEAD','checkout','detached'],
      negativeKeywords: [], requires: ['git-commit'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-merge', label: 'Merge strategies',
      description: 'Fast-forward vs three-way merge vs squash; when each applies.',
      tier: 'Mid', keywords: ['merge','fast-forward','three-way','squash','conflict','ours','theirs'],
      negativeKeywords: ['rebase'], requires: ['git-branch'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-rebase', label: 'Rebase & history rewriting',
      description: 'Interactive rebase, fixup, reorder; golden rule of rebasing.',
      tier: 'Mid', keywords: ['rebase','interactive','fixup','squash','cherry-pick','history','amend'],
      negativeKeywords: ['merge commit'], requires: ['git-branch'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-remote', label: 'Remotes & fetch/pull/push',
      description: 'Remote tracking branches, origin, fetch vs pull distinction.',
      tier: 'Mid', keywords: ['remote','origin','fetch','pull','push','tracking','upstream'],
      negativeKeywords: [], requires: ['git-branch'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-reflog', label: 'Reflog & recovery',
      description: 'Using reflog to recover lost commits, detached HEAD recovery.',
      tier: 'Senior', keywords: ['reflog','recover','lost commit','reset','ORIG_HEAD'],
      negativeKeywords: [], requires: ['git-commit','git-branch'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-hooks', label: 'Git hooks & automation',
      description: 'Pre-commit, pre-push, commit-msg hooks; bypassing with --no-verify.',
      tier: 'Senior', keywords: ['hook','pre-commit','pre-push','commit-msg','husky','lint-staged'],
      negativeKeywords: [], requires: ['git-commit'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'git-objects', label: 'Object model (blob/tree/commit/tag)',
      description: 'Content-addressed storage: blobs, trees, commits, annotated tags.',
      tier: 'Senior', keywords: ['blob','tree','object','SHA','pack','content-addressed','plumbing'],
      negativeKeywords: [], requires: ['git-commit'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
  ],
});

// ---------------------------------------------------------------------------
// Gradle
// ---------------------------------------------------------------------------
export const GRADLE_DOMAIN: Domain = hydrateGenerated({
  name: 'Gradle',
  root: 'gradle-build',
  grounded: true,
  nodes: [
    { id: 'gradle-build', label: 'Build lifecycle & tasks',
      description: 'Initialization, configuration, and execution phases; task DAG.',
      tier: 'Junior', keywords: ['task','lifecycle','phase','build','run','assemble','check'],
      negativeKeywords: [], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'gradle-deps', label: 'Dependency configurations',
      description: 'implementation vs api vs runtimeOnly vs compileOnly scopes.',
      tier: 'Junior', keywords: ['implementation','api','runtimeOnly','compileOnly','testImplementation','scope'],
      negativeKeywords: ['maven scope'], requires: ['gradle-build'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'gradle-multiproject', label: 'Multi-project builds',
      description: 'settings.gradle, subprojects, project dependencies, allprojects.',
      tier: 'Mid', keywords: ['subproject','settings','allprojects','project dependency','include','composite'],
      negativeKeywords: [], requires: ['gradle-build'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'gradle-incremental', label: 'Incremental build & caching',
      description: 'UP-TO-DATE checks, build cache, task inputs/outputs fingerprinting.',
      tier: 'Mid', keywords: ['incremental','UP-TO-DATE','cache','inputs','outputs','fingerprint','cached'],
      negativeKeywords: [], requires: ['gradle-build'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'gradle-plugins', label: 'Plugin system',
      description: 'Binary plugins, script plugins, convention plugins, buildSrc.',
      tier: 'Mid', keywords: ['plugin','apply','buildSrc','convention','binary plugin','extension'],
      negativeKeywords: [], requires: ['gradle-build'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'gradle-resolution', label: 'Dependency resolution & conflicts',
      description: 'Version conflict resolution, force, strictly, reject, BOM import.',
      tier: 'Senior', keywords: ['conflict','force','strictly','reject','BOM','platform','resolution strategy'],
      negativeKeywords: [], requires: ['gradle-deps'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'gradle-custom-task', label: 'Custom task types & workers',
      description: 'Writing typed task classes, worker API, task parallelism.',
      tier: 'Senior', keywords: ['DefaultTask','TaskAction','worker','parallel','task type','lazy configuration'],
      negativeKeywords: [], requires: ['gradle-build','gradle-incremental'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
  ],
});

// ---------------------------------------------------------------------------
// Docker
// ---------------------------------------------------------------------------
export const DOCKER_DOMAIN: Domain = hydrateGenerated({
  name: 'Docker',
  root: 'docker-image',
  grounded: true,
  nodes: [
    { id: 'docker-image', label: 'Images & layers',
      description: 'Union filesystem, layer caching, image vs container distinction.',
      tier: 'Junior', keywords: ['image','layer','union filesystem','overlay','pull','tag'],
      negativeKeywords: [], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'docker-dockerfile', label: 'Dockerfile instructions',
      description: 'FROM, RUN, COPY, ADD, CMD vs ENTRYPOINT, ENV, ARG, EXPOSE.',
      tier: 'Junior', keywords: ['Dockerfile','FROM','RUN','COPY','CMD','ENTRYPOINT','ENV','ARG','EXPOSE'],
      negativeKeywords: [], requires: ['docker-image'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'docker-networking', label: 'Container networking',
      description: 'Bridge, host, overlay networks; port publishing; DNS resolution.',
      tier: 'Mid', keywords: ['bridge','host network','overlay','port','publish','expose','DNS','-p'],
      negativeKeywords: [], requires: ['docker-image'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'docker-volumes', label: 'Volumes & bind mounts',
      description: 'Named volumes vs bind mounts vs tmpfs; persistence and sharing.',
      tier: 'Mid', keywords: ['volume','bind mount','tmpfs','persist','-v','--mount'],
      negativeKeywords: [], requires: ['docker-image'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'docker-compose', label: 'Docker Compose',
      description: 'Multi-container apps, service dependencies, health checks, profiles.',
      tier: 'Mid', keywords: ['compose','service','depends_on','healthcheck','profile','scale','override'],
      negativeKeywords: [], requires: ['docker-networking','docker-volumes'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'docker-multistage', label: 'Multi-stage builds',
      description: 'Build vs runtime stages, minimising final image size, COPY --from.',
      tier: 'Senior', keywords: ['multi-stage','builder','COPY --from','distroless','scratch','slim'],
      negativeKeywords: [], requires: ['docker-dockerfile'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'docker-security', label: 'Container security',
      description: 'Non-root user, read-only filesystem, capabilities, seccomp, secrets.',
      tier: 'Senior', keywords: ['non-root','USER','capability','seccomp','secret','read-only','privileged'],
      negativeKeywords: [], requires: ['docker-dockerfile'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
  ],
});

// ---------------------------------------------------------------------------
// npm / Node packaging
// ---------------------------------------------------------------------------
export const NPM_DOMAIN: Domain = hydrateGenerated({
  name: 'npm / Node packaging',
  root: 'npm-package',
  grounded: true,
  nodes: [
    { id: 'npm-package', label: 'package.json & package-lock.json',
      description: 'Manifest fields, lockfile purpose, deterministic installs.',
      tier: 'Junior', keywords: ['package.json','package-lock','lockfile','manifest','dependencies','devDependencies'],
      negativeKeywords: [], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'npm-semver', label: 'SemVer & version ranges',
      description: 'Major.minor.patch semantics, ^ vs ~ vs exact vs *, pre-release tags.',
      tier: 'Junior', keywords: ['semver','major','minor','patch','caret','tilde','range','pre-release'],
      negativeKeywords: [], requires: ['npm-package'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'npm-scripts', label: 'npm scripts & lifecycle',
      description: 'pre/post hooks, script composition, env vars, PATH augmentation.',
      tier: 'Mid', keywords: ['scripts','preinstall','postinstall','lifecycle','npm run','PATH','cross-env'],
      negativeKeywords: [], requires: ['npm-package'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'npm-workspaces', label: 'Workspaces & monorepos',
      description: 'npm workspaces, hoisting, cross-package linking.',
      tier: 'Mid', keywords: ['workspace','monorepo','hoist','link','turborepo','nx','pnpm'],
      negativeKeywords: [], requires: ['npm-package'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'npm-registry', label: 'Registry & publishing',
      description: 'npm publish, .npmrc, scoped packages, private registry, provenance.',
      tier: 'Mid', keywords: ['publish','registry','.npmrc','scope','private','token','provenance'],
      negativeKeywords: [], requires: ['npm-package'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'npm-resolution', label: 'Dependency resolution & deduplication',
      description: 'How npm resolves version conflicts, dedup, peer deps, overrides.',
      tier: 'Senior', keywords: ['dedup','peer','override','resolution','phantom dep','hoisting algorithm'],
      negativeKeywords: [], requires: ['npm-semver'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'npm-audit', label: 'Security audit & patching',
      description: 'npm audit, audit fix, GHSA advisories, overrides for patch.',
      tier: 'Senior', keywords: ['audit','vulnerability','GHSA','CVE','npm audit fix','override'],
      negativeKeywords: [], requires: ['npm-package'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
  ],
});

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------
export const TS_DOMAIN: Domain = hydrateGenerated({
  name: 'TypeScript',
  root: 'ts-types',
  grounded: true,
  nodes: [
    { id: 'ts-types', label: 'Type system basics',
      description: 'Primitive types, union, intersection, literal types, type vs interface.',
      tier: 'Junior', keywords: ['type','interface','union','intersection','literal','primitive','any','unknown'],
      negativeKeywords: [], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'ts-narrowing', label: 'Narrowing & type guards',
      description: 'typeof, instanceof, discriminated unions, assertion functions, in operator.',
      tier: 'Junior', keywords: ['narrowing','typeof','instanceof','discriminated union','type guard','in'],
      negativeKeywords: [], requires: ['ts-types'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'ts-generics', label: 'Generics',
      description: 'Generic functions, classes, constraints, default type params.',
      tier: 'Mid', keywords: ['generic','T','constraint','extends','keyof','infer','default'],
      negativeKeywords: [], requires: ['ts-types'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'ts-utility', label: 'Utility types',
      description: 'Partial, Required, Readonly, Pick, Omit, Record, ReturnType, Awaited.',
      tier: 'Mid', keywords: ['Partial','Required','Readonly','Pick','Omit','Record','ReturnType','Awaited','Extract'],
      negativeKeywords: [], requires: ['ts-generics'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'ts-config', label: 'tsconfig & compilation',
      description: 'strict mode, module resolution, paths, project references, isolatedModules.',
      tier: 'Mid', keywords: ['tsconfig','strict','module resolution','paths','project references','isolatedModules','target'],
      negativeKeywords: [], requires: ['ts-types'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'ts-mapped', label: 'Mapped & conditional types',
      description: 'Mapped types with as clauses, conditional types, infer in conditions.',
      tier: 'Senior', keywords: ['mapped type','conditional type','infer','distributive','template literal type','as clause'],
      negativeKeywords: [], requires: ['ts-generics','ts-utility'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'ts-decorators', label: 'Decorators & metadata',
      description: 'Class, method, parameter decorators; reflect-metadata; stage 3 spec.',
      tier: 'Senior', keywords: ['decorator','reflect-metadata','experimentalDecorators','class decorator','method decorator'],
      negativeKeywords: [], requires: ['ts-types'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
  ],
});

// ---------------------------------------------------------------------------
// SQL
// ---------------------------------------------------------------------------
export const SQL_DOMAIN: Domain = hydrateGenerated({
  name: 'SQL',
  root: 'sql-select',
  grounded: true,
  nodes: [
    { id: 'sql-select', label: 'SELECT & filtering',
      description: 'SELECT, WHERE, DISTINCT, ORDER BY, LIMIT; NULL handling.',
      tier: 'Junior', keywords: ['SELECT','WHERE','DISTINCT','ORDER BY','LIMIT','NULL','IS NULL','LIKE'],
      negativeKeywords: [], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'sql-joins', label: 'JOINs',
      description: 'INNER, LEFT, RIGHT, FULL OUTER, CROSS, SELF joins; join conditions.',
      tier: 'Junior', keywords: ['JOIN','INNER JOIN','LEFT JOIN','OUTER JOIN','CROSS JOIN','ON','USING'],
      negativeKeywords: [], requires: ['sql-select'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'sql-aggregates', label: 'Aggregation & GROUP BY',
      description: 'COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING, ROLLUP.',
      tier: 'Mid', keywords: ['GROUP BY','HAVING','COUNT','SUM','AVG','aggregate','ROLLUP'],
      negativeKeywords: [], requires: ['sql-select'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'sql-subqueries', label: 'Subqueries & CTEs',
      description: 'Correlated subqueries, CTE (WITH), recursive CTE, EXISTS vs IN.',
      tier: 'Mid', keywords: ['subquery','CTE','WITH','EXISTS','IN','correlated','recursive'],
      negativeKeywords: [], requires: ['sql-joins','sql-aggregates'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'sql-indexes', label: 'Indexes & query planning',
      description: 'B-tree, hash, composite indexes; EXPLAIN; covering index; selectivity.',
      tier: 'Mid', keywords: ['index','B-tree','composite','EXPLAIN','covering index','selectivity','scan type'],
      negativeKeywords: [], requires: ['sql-select'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'sql-transactions', label: 'Transactions & isolation',
      description: 'ACID, isolation levels, dirty read, phantom read, MVCC, SAVEPOINT.',
      tier: 'Senior', keywords: ['ACID','transaction','isolation','dirty read','phantom','MVCC','SAVEPOINT','ROLLBACK'],
      negativeKeywords: [], requires: ['sql-select'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'sql-window', label: 'Window functions',
      description: 'OVER, PARTITION BY, RANK, ROW_NUMBER, LAG/LEAD, ROWS BETWEEN.',
      tier: 'Senior', keywords: ['window function','OVER','PARTITION BY','RANK','ROW_NUMBER','LAG','LEAD','frame'],
      negativeKeywords: [], requires: ['sql-aggregates'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
  ],
});

// ---------------------------------------------------------------------------
// Node.js
// ---------------------------------------------------------------------------
export const NODEJS_DOMAIN: Domain = hydrateGenerated({
  name: 'Node.js',
  root: 'node-event-loop',
  grounded: true,
  nodes: [
    { id: 'node-event-loop', label: 'Event loop & async model',
      description: 'How Node.js handles I/O with a single-threaded event loop, libuv, and the call stack.',
      tier: 'Junior', keywords: ['event loop','call stack','libuv','non-blocking','I/O','tick','microtask'],
      negativeKeywords: ['thread'], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'node-modules', label: 'Module system (CJS vs ESM)',
      description: 'CommonJS require() vs ES module import/export; how Node resolves modules.',
      tier: 'Junior', keywords: ['require','module.exports','import','export','ESM','CommonJS','package.json type'],
      negativeKeywords: [], requires: ['node-event-loop'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 1, row: 0 },
    { id: 'node-streams', label: 'Streams & buffers',
      description: 'Readable/Writable/Transform streams; backpressure; piping; Buffer vs string.',
      tier: 'Mid', keywords: ['stream','pipe','backpressure','Buffer','Readable','Writable','Transform','chunk'],
      negativeKeywords: [], requires: ['node-event-loop'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 1 },
    { id: 'node-http', label: 'HTTP server & middleware',
      description: 'Creating HTTP servers with http.createServer(); request/response lifecycle; Express middleware pattern.',
      tier: 'Junior', keywords: ['createServer','req','res','middleware','Express','route','status code','header'],
      negativeKeywords: [], requires: ['node-modules'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 1, row: 1 },
    { id: 'node-fs', label: 'File system API',
      description: 'fs promises API: readFile, writeFile, mkdir, stat; path module; async vs sync variants.',
      tier: 'Junior', keywords: ['fs','readFile','writeFile','mkdir','path.join','stat','async','promises'],
      negativeKeywords: [], requires: ['node-event-loop'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 2, row: 0 },
    { id: 'node-errors', label: 'Error handling & process',
      description: 'Error-first callbacks; unhandledRejection; process.exit; domains vs try/catch in async code.',
      tier: 'Mid', keywords: ['unhandledRejection','uncaughtException','process.exit','try/catch','error-first','callback'],
      negativeKeywords: [], requires: ['node-event-loop'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 2, row: 1 },
    { id: 'node-cluster', label: 'Cluster & child processes',
      description: 'cluster module for multi-core; child_process.spawn/fork; worker_threads vs cluster.',
      tier: 'Senior', keywords: ['cluster','child_process','spawn','fork','worker_threads','IPC','multi-core'],
      negativeKeywords: [], requires: ['node-event-loop','node-errors'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 1, row: 2 },
  ],
});

// ---------------------------------------------------------------------------
// React
// ---------------------------------------------------------------------------
export const REACT_DOMAIN: Domain = hydrateGenerated({
  name: 'React',
  root: 'react-component',
  grounded: true,
  nodes: [
    { id: 'react-component', label: 'Component model & JSX',
      description: 'Function components as pure UI functions; JSX transpilation; props vs children; component tree.',
      tier: 'Junior', keywords: ['component','JSX','props','children','function component','render','tree'],
      negativeKeywords: ['class component'], requires: [], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 0 },
    { id: 'react-state', label: 'State & useState',
      description: 'Local component state with useState; immutable updates; batched re-renders; state lifting.',
      tier: 'Junior', keywords: ['useState','state','setState','immutable','re-render','lift state','batching'],
      negativeKeywords: [], requires: ['react-component'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 1, row: 0 },
    { id: 'react-effects', label: 'useEffect & lifecycle',
      description: 'Side effects with useEffect; dependency array; cleanup; when effects run vs render.',
      tier: 'Junior', keywords: ['useEffect','dependency array','cleanup','mount','unmount','side effect','subscription'],
      negativeKeywords: [], requires: ['react-state'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 1 },
    { id: 'react-context', label: 'Context & useContext',
      description: 'Sharing data across the tree without prop drilling; createContext; Provider; consumer re-renders.',
      tier: 'Mid', keywords: ['createContext','useContext','Provider','Consumer','prop drilling','re-render'],
      negativeKeywords: [], requires: ['react-state'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 1, row: 1 },
    { id: 'react-hooks', label: 'Custom hooks & rules of hooks',
      description: 'Extracting logic into custom hooks; rules: top-level only, no conditionals; useRef, useMemo, useCallback.',
      tier: 'Mid', keywords: ['custom hook','useRef','useMemo','useCallback','rules of hooks','memoization'],
      negativeKeywords: [], requires: ['react-effects','react-context'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 2 },
    { id: 'react-reconciliation', label: 'Reconciliation & virtual DOM',
      description: 'Diffing algorithm; key prop importance; fiber architecture; React.memo; when to optimise.',
      tier: 'Mid', keywords: ['reconciliation','virtual DOM','diffing','key','React.memo','fiber','rerender','optimise'],
      negativeKeywords: [], requires: ['react-effects'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 1, row: 2 },
    { id: 'react-patterns', label: 'Advanced patterns',
      description: 'Compound components, render props, HOCs, controlled vs uncontrolled inputs, Suspense, lazy.',
      tier: 'Senior', keywords: ['compound component','render prop','HOC','controlled','uncontrolled','Suspense','lazy','portal'],
      negativeKeywords: [], requires: ['react-hooks','react-reconciliation'], levels: [], eat: { entity: 'concept', action: 'recall', target: 'node' }, col: 0, row: 3 },
  ],
});
