import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { useNavigate } from 'react-router-dom';
import { Award } from 'lucide-react';

export default function Login() {
  const navigate = useNavigate();
    const [email, setEmail] = useState('');
      const [password, setPassword] = useState('');
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState<string | null>(null);
            const [mode, setMode] = useState<'login' | 'signup'>('login');

              async function handleSubmit(e: React.FormEvent) {
                  e.preventDefault();
                      setLoading(true);
                          setError(null);
                              const { error } = mode === 'login'
                                    ? await supabase.auth.signInWithPassword({ email, password })
                                          : await supabase.auth.signUp({ email, password });
                                              if (error) {
                                                    setError(error.message);
                                                        } else {
                                                              navigate('/');
                                                                  }
                                                                      setLoading(false);
                                                                        }

                                                                          return (
                                                                              <div className="min-h-screen bg-gray-50 flex items-center justify-center">
                                                                                    <div className="bg-white rounded-2xl border border-gray-200 p-8 w-full max-w-sm shadow-sm">
                                                                                            <div className="flex items-center justify-center gap-2 mb-6">
                                                                                                      <Award className="w-7 h-7 text-indigo-600" />
                                                                                                                <h1 className="text-2xl font-bold text-gray-900">WitnessSkills</h1>
                                                                                                                        </div>
                                                                                                                                <h2 className="text-center text-gray-600 mb-6 text-sm">
                                                                                                                                          {mode === 'login' ? 'Sign in to your account' : 'Create a new account'}
                                                                                                                                                  </h2>
                                                                                                                                                          <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                    <div>
                                                                                                                                                                                <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                                                                                                                                                                                            <input
                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                      value={email}
                                                                                                                                                                                                                                                    onChange={e => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                placeholder="you@example.com"
                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                  value={password}
                                                                                                                                                                                                                                                                                                                                                                                                onChange={e => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Your password"
                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && <p className="text-sm text-red-600">{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-700 disabled:opacity-50 text-sm font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? 'Loading...' : mode === 'login' ? 'Sign In' : 'Sign Up'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-center text-sm text-gray-500 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {mode === 'login' ? "Don't have an account? " : 'Already have an account? '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => setMode(m => m === 'login' ? 'signup' : 'login')} className="text-indigo-600 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {mode === 'login' ? 'Sign up' : 'Sign in'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
