import { useAuth } from '../context/AuthContext';
import { Link } from 'react-router-dom';
import { ArrowLeft, User } from 'lucide-react';

export default function Profile() {
  const { user, signOut } = useAuth();

    return (
        <div className="min-h-screen bg-gray-50">
              <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center gap-4">
                      <Link to="/" className="text-gray-400 hover:text-gray-600">
                                <ArrowLeft className="w-5 h-5" />
                                        </Link>
                                                <div className="flex items-center gap-2">
                                                          <User className="w-5 h-5 text-indigo-600" />
                                                                    <h1 className="text-xl font-bold text-gray-900">Profile</h1>
                                                                            </div>
                                                                                  </header>
                                                                                        <main className="max-w-2xl mx-auto px-6 py-10">
                                                                                                <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                          <div className="flex items-center gap-4 mb-6">
                                                                                                                      <div className="w-16 h-16 rounded-full bg-indigo-100 flex items-center justify-center">
                                                                                                                                    <User className="w-8 h-8 text-indigo-600" />
                                                                                                                                                </div>
                                                                                                                                                            <div>
                                                                                                                                                                          <h2 className="text-lg font-semibold text-gray-900">{user?.email}</h2>
                                                                                                                                                                                        <p className="text-sm text-gray-500">Member since {user?.created_at ? new Date(user.created_at).toLocaleDateString() : 'N/A'}</p>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                        <div className="border-t border-gray-100 pt-4">
                                                                                                                                                                                                                                    <dl className="space-y-3">
                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                  <dt className="text-xs font-medium text-gray-500 uppercase tracking-wide">Email</dt>
                                                                                                                                                                                                                                                                                  <dd className="text-sm text-gray-900 mt-1">{user?.email}</dd>
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                              <dt className="text-xs font-medium text-gray-500 uppercase tracking-wide">User ID</dt>
                                                                                                                                                                                                                                                                                                                                              <dd className="text-sm text-gray-900 mt-1 font-mono">{user?.id}</dd>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                        </dl>
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6 pt-4 border-t border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={signOut}
                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full border border-red-200 text-red-600 py-2 rounded-lg hover:bg-red-50 text-sm font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Sign Out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
