import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import { Link } from 'react-router-dom';
import { ArrowLeft, Plus, BookOpen } from 'lucide-react';

interface Skill {
  id: string;
    name: string;
      level: string;
        evidence: string;
          created_at: string;
          }

          export default function Skills() {
            const { user } = useAuth();
              const [skills, setSkills] = useState<Skill[]>([]);
                const [loading, setLoading] = useState(true);
                  const [newSkill, setNewSkill] = useState({ name: '', level: 'beginner', evidence: '' });
                    const [adding, setAdding] = useState(false);

                      useEffect(() => {
                          if (user) loadSkills();
                            }, [user]);

                              async function loadSkills() {
                                  const { data, error } = await supabase
                                        .from('skills')
                                              .select('*')
                                                    .eq('user_id', user!.id)
                                                          .order('created_at', { ascending: false });
                                                              if (!error && data) setSkills(data);
                                                                  setLoading(false);
                                                                    }

                                                                      async function addSkill() {
                                                                          if (!newSkill.name.trim()) return;
                                                                              const { error } = await supabase.from('skills').insert({
                                                                                    user_id: user!.id,
                                                                                          ...newSkill,
                                                                                              });
                                                                                                  if (!error) {
                                                                                                        setNewSkill({ name: '', level: 'beginner', evidence: '' });
                                                                                                              setAdding(false);
                                                                                                                    loadSkills();
                                                                                                                        }
                                                                                                                          }
                                                                                                                          
                                                                                                                            return (
                                                                                                                                <div className="min-h-screen bg-gray-50">
                                                                                                                                      <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center gap-4">
                                                                                                                                              <Link to="/" className="text-gray-400 hover:text-gray-600">
                                                                                                                                                        <ArrowLeft className="w-5 h-5" />
                                                                                                                                                                </Link>
                                                                                                                                                                        <div className="flex items-center gap-2">
                                                                                                                                                                                  <BookOpen className="w-5 h-5 text-indigo-600" />
                                                                                                                                                                                            <h1 className="text-xl font-bold text-gray-900">Skills</h1>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                          </header>
                                                                                                                                                                                                                <main className="max-w-4xl mx-auto px-6 py-10">
                                                                                                                                                                                                                        <div className="flex justify-between items-center mb-6">
                                                                                                                                                                                                                                  <h2 className="text-xl font-semibold text-gray-900">My Skills</h2>
                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                        onClick={() => setAdding(!adding)}
                                                                                                                                                                                                                                                                    className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700"
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                          <Plus className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                      Add Skill
                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                {adding && (
                                                                                                                                                                                                                                                                                                                                          <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
                                                                                                                                                                                                                                                                                                                                                      <h3 className="font-semibold text-gray-900 mb-4">New Skill</h3>
                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Skill name"
                                                                                                                                                                                                                                                                                                                                                                                                                                value={newSkill.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={e => setNewSkill(s => ({ ...s, name: e.target.value }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={newSkill.level}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={e => setNewSkill(s => ({ ...s, level: e.target.value }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="beginner">Beginner</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="intermediate">Intermediate</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="advanced">Advanced</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="expert">Expert</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Evidence (links, descriptions, examples)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={newSkill.evidence}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={e => setNewSkill(s => ({ ...s, evidence: e.target.value }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={addSkill} className="bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 text-sm">Save</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setAdding(false)} className="border border-gray-300 px-4 py-2 rounded-lg hover:bg-gray-50 text-sm">Cancel</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-500">Loading...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : skills.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center py-16 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <BookOpen className="w-12 h-12 mx-auto mb-3 opacity-30" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>No skills yet. Add your first skill above.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {skills.map(skill => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={skill.id} className="bg-white rounded-xl border border-gray-200 p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-start justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="font-semibold text-gray-900">{skill.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs bg-indigo-100 text-indigo-700 px-2 py-1 rounded-full capitalize">{skill.level}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {skill.evidence && <p className="text-sm text-gray-500 mt-2">{skill.evidence}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
